let LANG = 'id';
let currentUtterance = null;

const UI = {
  id: {
    index: 'Indeks', soilArchive: 'The Soil Archive', subtitle: 'This is not a colour-matching chart. It is a sensory index for reading soil through texture, moisture, memory, and embodied farming knowledge.',
    logic: 'Touch → Quality → Archive', intro: 'Arsip ini disusun sebagai jembatan antara fan card fisik, spesimen tanah taktil, dan catatan digital. Setiap entri dapat dibuka dari indeks ini atau melalui QR/NFC pada kartu dan spesimen.',
    voice: 'Putar catatan suara', note: 'Catatan Arsip', feels: 'Rasa', classification: 'Klasifikasi', source: 'Asal', related: 'Tanah Lain', version: 'v0.2 · tumbuh', contribute: 'Arsip ini masih tumbuh. Punya tanah untuk dititipkan? Hubungi kami.',
    usually: 'Biasanya ditemukan', crops: 'Tanaman yang mendukung'
  },
  en: {
    index: 'Index', soilArchive: 'The Soil Archive', subtitle: 'This is not a colour-matching chart. It is a sensory index for reading soil through texture, moisture, memory, and embodied farming knowledge.',
    logic: 'Touch → Quality → Archive', intro: 'This archive is designed as a bridge between the physical fan card, tactile soil specimens, and digital notes. Each entry can be accessed from this index or through QR/NFC on the card and specimen.',
    voice: 'Play voice note', note: 'Archive Note', feels: 'Feels', classification: 'Classification', source: 'Source', related: 'Related Entries', version: 'v0.2 · growing', contribute: 'This archive is still growing. Have soil to contribute? Get in touch.',
    usually: 'Usually found', crops: 'Often supports'
  }
};
const t = (key)=>UI[LANG][key];
const L = (obj)=> obj?.[LANG] || obj?.en || '';

const entries = [
  {
    id:'so-01', code:'SO-01', image:'assets/images/volcanic-ash.jpg',
    title:{id:'Abu Vulkanik',en:'Volcanic Ash'}, scientific:'Andosol · volcanic · mineral-rich',
    feelsShort:{id:'Lunak · Gelap · Berpori · Subur',en:'Soft · Dark · Porous · Fertile'},
    usual:{id:'Lereng gunung, dataran tinggi vulkanik, lahan terasering',en:'Mountain slopes, volcanic uplands, terraced farms'}, crops:{id:'Sayuran, kopi, teh, cabai',en:'Vegetables, coffee, tea, chili'},
    quote:{id:'Tanah vulkanik terasa ringan namun menyimpan kehidupan. Ia mudah hancur di tangan, tetapi kuat menopang akar.',en:'Volcanic soil feels light yet full of life. It breaks easily in the hand, but holds roots firmly.'},
    voiceName:{id:'Catatan Abu Vulkanik',en:'Volcanic Ash Note'}, duration:'01:18', language:{id:'Indonesia / Inggris',en:'Indonesian / English'},
    note:{id:'Abu vulkanik dibaca sebagai tanah yang berpori, gelap, dan kaya mineral. Dalam praktik pertanian, kualitas ini sering dikaitkan dengan kesuburan dan kemampuan tanah menyimpan kelembapan tanpa terasa terlalu berat.',en:'Volcanic ash soil is read as porous, dark, and mineral-rich. In farming practice, this quality is often associated with fertility and the ability to hold moisture without feeling overly heavy.'},
    feels:[['Tekstur','Texture','Lunak, remah, mudah pecah','Soft, crumbly, easily broken'],['Kelembapan','Moisture','Menahan air sedang, tidak becek','Moderately retentive, not muddy'],['Berat','Weight','Ringan sampai sedang','Light to medium'],['Aroma','Smell','Mineral, tanah segar, sedikit organik','Mineral, fresh earth, slightly organic']],
    classification:[['Jenis','Type','Andosol / tanah vulkanik','Andosol / volcanic soil'],['Struktur','Structure','Berpori, granular, remah','Porous, granular, crumbly'],['Drainase','Drainage','Baik, tetap menyimpan kelembapan','Good, while retaining moisture'],['Catatan','Note','Umum pada lahan tinggi vulkanik di Indonesia','Common in volcanic highlands in Indonesia']],
    source:[['Kategori','Category','Kualitas tanah mineral-subur','Mineral-fertile soil quality'],['Konteks','Context','Dataran tinggi dan lahan terasering','Highland and terraced farming'],['Metode baca','Reading method','Warna, pori, remah, kelembapan','Colour, pores, crumbs, moisture'],['Akses','Access','Fan card, spesimen taktil, QR/NFC','Fan card, tactile specimen, QR/NFC']],
    related:['so-04','so-05','so-03']
  },
  {
    id:'so-02', code:'SO-02', image:'assets/images/holding-water.jpg', title:{id:'Tanah Lembap',en:'Holding Water'}, scientific:'Alluvial · clay-rich · loamy', feelsShort:{id:'Sejuk · Padat · Lembap · Berat',en:'Cool · Dense · Moist · Heavy'}, usual:{id:'Sawah irigasi dataran rendah',en:'Lowland irrigated rice fields'}, crops:{id:'Padi, talas, kangkung',en:'Rice, taro, water spinach'},
    quote:{id:'Tanah ini menahan air seperti spons. Dipegang lembap, tidak pernah benar-benar kering.',en:'This soil holds water like a sponge. Damp in the hand, never truly dry.'}, voiceName:{id:'Catatan Tanah Lembap',en:'Holding Water Note'}, duration:'01:24', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Tanah lembap menunjukkan kemampuan tanah menyimpan air setelah hujan atau irigasi. Kualitas ini tidak hanya dibaca sebagai basah, tetapi sebagai tanda bahwa tanah masih mampu mendukung pertumbuhan tanaman.',en:'Holding water describes soil that keeps moisture after rain or irrigation. It is not only read as wetness, but as a sign that the ground can continue supporting crop growth.'},
    feels:[['Tekstur','Texture','Lembap, halus, mudah dibentuk','Damp, fine, easily shaped'],['Suhu','Temperature','Terasa sejuk di tangan','Cool to the hand'],['Tekanan','Pressure','Memadat saat ditekan','Compacts under pressure'],['Aroma','Smell','Tanah basah, organik, sedikit anaerobik','Wet earth, organic, slightly anaerobic']],
    classification:[['Jenis','Type','Alluvial, liat, lempung berpasir','Alluvial, clay-rich, loamy'],['Struktur','Structure','Padat, menahan air','Dense, water-retentive'],['Drainase','Drainage','Lambat sampai sedang','Slow to moderate'],['Risiko','Risk','Terlalu basah dapat menghambat akar','Too much water can restrict roots']],
    source:[['Kategori','Category','Kualitas kelembapan tanah','Moisture-related soil quality'],['Konteks','Context','Sawah dataran rendah / irigasi','Lowland irrigated rice fields'],['Metode baca','Reading method','Sentuhan, berat, kilap, bau','Touch, weight, shine, smell'],['Tanaman','Crops','Padi, talas, kangkung','Rice, taro, water spinach']], related:['so-07','so-06','so-08']
  },
  {
    id:'so-03', code:'SO-03', image:'assets/images/root-mat.jpg', title:{id:'Jalinan Akar',en:'Root Mat'}, scientific:'Rhizospheric · organic · fibrous', feelsShort:{id:'Kusut · Lentur · Hidup',en:'Tangled · Springy · Alive'}, usual:{id:'Tepi padang rumput, bedengan lama, lahan kaya kompos',en:'Grassland edges, old crop beds, compost-rich plots'}, crops:{id:'Jahe, kunyit, herba, pohon buah',en:'Ginger, turmeric, herbs, fruit trees'},
    quote:{id:'Akar menjadi catatan hidup di dalam tanah. Ia menunjukkan di mana tanaman pernah mencari air dan makanan.',en:'Roots become a living record inside the soil. They show where plants have searched for water and food.'}, voiceName:{id:'Catatan Jalinan Akar',en:'Root Mat Note'}, duration:'01:12', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Jalinan akar menandai hubungan antara struktur tanah dan kehidupan tanaman. Kualitas ini dibaca melalui serabut, lapisan organik, dan rasa lentur ketika tanah disentuh.',en:'Root mat marks the relationship between soil structure and plant life. This quality is read through fibres, organic layers, and the springy feeling of soil in the hand.'},
    feels:[['Tekstur','Texture','Berserat, kusut, berlapis','Fibrous, tangled, layered'],['Respon','Response','Lentur, tidak langsung hancur','Springy, does not immediately break'],['Aroma','Smell','Kompos, akar, tanah hidup','Compost, roots, living soil'],['Tanda visual','Visual sign','Serabut akar terlihat jelas','Visible fine roots']],
    classification:[['Zona','Zone','Rhizosphere / zona perakaran','Rhizosphere / root zone'],['Bahan','Material','Organik, akar, humus','Organic matter, roots, humus'],['Struktur','Structure','Terikat oleh jaringan akar','Held together by root networks'],['Fungsi','Function','Menjaga agregat dan pori tanah','Supports aggregates and soil pores']],
    source:[['Kategori','Category','Kualitas biologis tanah','Biological soil quality'],['Konteks','Context','Bedengan lama, lahan kompos, tepi rumput','Old beds, compost plots, grass edges'],['Metode baca','Reading method','Akar, bau, serat, daya lentur','Roots, smell, fibres, springiness'],['Tanaman','Crops','Rimpang, herba, pohon buah','Rhizomes, herbs, fruit trees']], related:['so-05','so-01','so-04']
  },
  {
    id:'so-04', code:'SO-04', image:'assets/images/fresh-turn.jpg', title:{id:'Tanah Gembur',en:'Fresh Turn'}, scientific:'Cultivated · aerated', feelsShort:{id:'Lepas · Remah · Sedang',en:'Loose · Crumbly · Mid-weight'}, usual:{id:'Lahan baru diolah, bedengan siap tanam',en:'Recently worked plots, prepared seedbeds'}, crops:{id:'Sebagian besar tanaman saat tanam, sayuran daun, bibit',en:'Most crops at planting, leafy greens, seedlings'},
    quote:{id:'Saat tanah baru dibalik, yang tersembunyi muncul: bau, akar kecil, kelembapan, dan kesiapan tanam.',en:'When soil is freshly turned, what was hidden appears: smell, small roots, moisture, and readiness for planting.'}, voiceName:{id:'Catatan Tanah Gembur',en:'Fresh Turn Note'}, duration:'01:20', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Tanah gembur adalah kualitas yang sering muncul setelah pengolahan tanah. Ia dibaca melalui remah, rongga udara, warna yang bervariasi, dan aroma tanah yang baru terbuka.',en:'Fresh turn appears after soil preparation. It is read through crumbs, air spaces, colour variation, and the smell of newly opened ground.'},
    feels:[['Tekstur','Texture','Gembur, remah, tidak terlalu halus','Loose, crumbly, not too fine'],['Udara','Air','Banyak rongga kecil','Many small air spaces'],['Kelembapan','Moisture','Seimbang, tidak becek','Balanced, not muddy'],['Aroma','Smell','Segar, baru dibuka','Fresh, newly opened']],
    classification:[['Kondisi','Condition','Cultivated / aerated soil','Cultivated / aerated soil'],['Struktur','Structure','Remah dan lepas','Crumbly and loose'],['Drainase','Drainage','Sedang sampai baik','Moderate to good'],['Catatan','Note','Sering menjadi tanda bedengan siap tanam','Often signals a prepared planting bed']],
    source:[['Kategori','Category','Kualitas persiapan tanam','Planting-preparation quality'],['Konteks','Context','Bedengan, lahan baru dicangkul / dibajak','Seedbeds, newly hoed or tilled land'],['Metode baca','Reading method','Sentuh, bau, warna, remah','Touch, smell, colour, crumbs'],['Tanaman','Crops','Bibit, sayuran daun, tanaman awal','Seedlings, leafy greens, early crops']], related:['so-01','so-10','so-03']
  },
  {
    id:'so-05', code:'SO-05', image:'assets/images/deep-root.jpg', title:{id:'Akar Dalam',en:'Deep Root'}, scientific:'Humic · organic-rich · living', feelsShort:{id:'Gelap · Remah · Berjaring',en:'Dark · Crumbly · Webbed'}, usual:{id:'Tanah hutan lama, lahan istirahat, plot kaya kompos',en:'Old forest soil, well-rested fields, compost-fed plots'}, crops:{id:'Tembakau, kopi, pohon buah, sayuran berakar dalam',en:'Tobacco, coffee, fruit trees, deep-rooted vegetables'},
    quote:{id:'Akar dalam menunjukkan bahwa tanah tidak hanya berada di permukaan. Kehidupan bekerja pelan di bawahnya.',en:'Deep roots show that soil is not only the surface. Life works slowly underneath.'}, voiceName:{id:'Catatan Akar Dalam',en:'Deep Root Note'}, duration:'01:16', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Akar dalam menandai hubungan antara kedalaman tanah, bahan organik, dan kekuatan tanaman. Kualitas ini sering dibaca dari warna gelap, jejak akar, dan rasa tanah yang remah tetapi terikat.',en:'Deep root marks the relationship between soil depth, organic matter, and plant strength. This quality is often read through dark colour, root traces, and soil that feels crumbly yet connected.'},
    feels:[['Tekstur','Texture','Remah, berakar, sedikit berserat','Crumbly, rooted, slightly fibrous'],['Warna','Colour','Gelap, kaya bahan organik','Dark, rich in organic matter'],['Kelembapan','Moisture','Stabil di bawah permukaan','Stable below the surface'],['Aroma','Smell','Humus, daun lapuk, tanah hidup','Humus, decayed leaves, living soil']],
    classification:[['Jenis','Type','Humic / organic-rich soil','Humic / organic-rich soil'],['Struktur','Structure','Agregat remah dengan jejak akar','Crumb aggregates with root traces'],['Fungsi','Function','Mendukung tanaman berakar dalam','Supports deep-rooted plants'],['Catatan','Note','Menunjukkan kontinuitas antara tanah dan akar','Shows continuity between soil and roots']],
    source:[['Kategori','Category','Kualitas kedalaman dan organik','Depth and organic quality'],['Konteks','Context','Lahan istirahat, kebun, tanah hutan lama','Rested fields, gardens, old forest soil'],['Metode baca','Reading method','Akar, warna, bau, kedalaman','Roots, colour, smell, depth'],['Tanaman','Crops','Kopi, tembakau, pohon buah','Coffee, tobacco, fruit trees']], related:['so-03','so-01','so-04']
  },
  {
    id:'so-06', code:'SO-06', image:'assets/images/river-silt.jpg', title:{id:'Endapan Sungai',en:'River Silt'}, scientific:'Silty · alluvial · fine deposit', feelsShort:{id:'Halus · Dingin · Licin · Lembut',en:'Smooth · Fine · Cool · Silky'}, usual:{id:'Tepi sungai, dataran banjir, saluran irigasi',en:'Riverbanks, floodplains, irrigation channels'}, crops:{id:'Padi, sayuran daun, pisang, sayuran',en:'Rice, leafy greens, banana, vegetables'}, quote:{id:'Endapan sungai terasa seperti lapisan halus. Ia membawa jejak air, arus, dan tanah dari tempat lain.',en:'River silt feels like a fine layer. It carries traces of water, flow, and soil from elsewhere.'}, voiceName:{id:'Catatan Endapan Sungai',en:'River Silt Note'}, duration:'01:10', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Endapan sungai dibaca melalui tekstur halus dan licin. Kualitas ini sering muncul pada area yang dipengaruhi aliran air, banjir, atau saluran irigasi.',en:'River silt is read through its fine and silky texture. It often appears in areas shaped by water flow, flooding, or irrigation channels.'}, feels:[['Tekstur','Texture','Sangat halus, licin, silky','Very fine, smooth, silky'],['Suhu','Temperature','Sejuk saat lembap','Cool when moist'],['Pola','Pattern','Lapisan dan alur air terlihat','Visible layers and flow marks'],['Kelembapan','Moisture','Mudah lembap, mudah berpindah','Easily moist, easily moved']], classification:[['Jenis','Type','Silty alluvial deposit','Silty alluvial deposit'],['Sumber','Origin','Endapan air / dataran banjir','Water deposit / floodplain'],['Drainase','Drainage','Bervariasi tergantung lapisan','Varies depending on layers'],['Catatan','Note','Subur tetapi bisa mudah tererosi','Fertile but can erode easily']], source:[['Kategori','Category','Kualitas endapan air','Water-deposit quality'],['Konteks','Context','Sungai, saluran irigasi, dataran banjir','Riverbanks, irrigation channels, floodplains'],['Metode baca','Reading method','Sentuh, alur, kelembutan, lapisan','Touch, flow marks, softness, layers'],['Tanaman','Crops','Padi, sayuran daun, pisang','Rice, leafy greens, banana']], related:['so-02','so-10','so-07']
  },
  {
    id:'so-07', code:'SO-07', image:'assets/images/sticky-clay.jpg', title:{id:'Liat Lekat',en:'Sticky Clay'}, scientific:'Clayey · vertic · water-retentive', feelsShort:{id:'Lengket · Berat · Padat',en:'Sticky · Heavy · Dense'}, usual:{id:'Sawah basah, cekungan dataran rendah, lahan irigasi',en:'Wet paddies, lowland basins, irrigated fields'}, crops:{id:'Padi, talas, lotus, kangkung',en:'Rice, taro, lotus, water spinach'}, quote:{id:'Tanah liat melekat di tangan dan alat. Ia menyimpan air, tetapi sulit dilepaskan ketika terlalu basah.',en:'Clay soil sticks to hands and tools. It holds water, but becomes difficult to release when too wet.'}, voiceName:{id:'Catatan Liat Lekat',en:'Sticky Clay Note'}, duration:'01:15', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Liat lekat dibaca melalui rasa lengket, berat, dan plastik. Kualitas ini menunjukkan tanah yang sangat menahan air, tetapi membutuhkan waktu dan tenaga saat diolah.',en:'Sticky clay is read through stickiness, weight, and plasticity. It shows soil that holds water strongly, but requires time and labour to work.'}, feels:[['Tekstur','Texture','Lengket, plastis, berat','Sticky, plastic, heavy'],['Basah','Wet','Mudah melekat dan membentuk','Sticks easily and forms shapes'],['Kering','Dry','Mengeras dan bisa retak','Hardens and may crack'],['Aroma','Smell','Tanah basah, mineral, berat','Wet earth, mineral, heavy']], classification:[['Jenis','Type','Clayey / vertic soil','Clayey / vertic soil'],['Struktur','Structure','Partikel halus, plastis','Fine particles, plastic'],['Drainase','Drainage','Lambat','Slow'],['Risiko','Risk','Sulit diolah jika terlalu basah atau terlalu kering','Difficult to work when too wet or too dry']], source:[['Kategori','Category','Kualitas liat dan retensi air','Clay and water-retention quality'],['Konteks','Context','Sawah, cekungan, dataran rendah','Paddies, basins, lowlands'],['Metode baca','Reading method','Lengket, berat, bekas jari, plastis','Stickiness, weight, finger marks, plasticity'],['Tanaman','Crops','Padi, talas, kangkung','Rice, taro, water spinach']], related:['so-02','so-08','so-06']
  },
  {
    id:'so-08', code:'SO-08', image:'assets/images/cracked-surface.jpg', title:{id:'Permukaan Retak',en:'Cracked Surface'}, scientific:'Vertisol · heavy clay · sun-dried', feelsShort:{id:'Kering · Retak · Rapuh · Keras',en:'Dry · Fissured · Brittle · Hard'}, usual:{id:'Sawah musim kering, lahan bera terbuka',en:'Dry-season paddies, exposed fallow ground'}, crops:{id:'Sorgum, biji-bijian tahan kering, masa istirahat',en:'Sorghum, drought-tolerant grains, after-rest'}, quote:{id:'Retakan adalah tanda waktu. Tanah sedang kehilangan air dan memperlihatkan batas-batasnya.',en:'Cracks are signs of time. The soil is losing water and revealing its edges.'}, voiceName:{id:'Catatan Permukaan Retak',en:'Cracked Surface Note'}, duration:'01:08', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Permukaan retak menunjukkan perubahan kelembapan yang ekstrem. Bagi petani, retakan dapat menjadi tanda kapan tanah terlalu kering, kapan perlu air, atau kapan lahan sedang beristirahat.',en:'Cracked surface indicates extreme moisture change. For farmers, cracks can signal dryness, irrigation timing, or a field in rest.'}, feels:[['Tekstur','Texture','Keras, rapuh, pecah berlapis','Hard, brittle, split into plates'],['Kelembapan','Moisture','Sangat kering di permukaan','Very dry at the surface'],['Pola','Pattern','Retakan lebar, seperti peta','Wide cracks, map-like'],['Suara','Sound','Rapuh saat diinjak atau dipatahkan','Brittle under foot or when broken']], classification:[['Jenis','Type','Vertisol / heavy clay','Vertisol / heavy clay'],['Kondisi','Condition','Sun-dried surface','Sun-dried surface'],['Drainase','Drainage','Lambat ketika basah, retak ketika kering','Slow when wet, cracks when dry'],['Catatan','Note','Terkait siklus basah-kering','Related to wet-dry cycles']], source:[['Kategori','Category','Kualitas kekeringan permukaan','Surface-dryness quality'],['Konteks','Context','Sawah kering, lahan bera, musim panas','Dry paddies, fallow land, hot season'],['Metode baca','Reading method','Retak, suara, resistensi, warna pucat','Cracks, sound, resistance, pale colour'],['Tanaman','Crops','Sorgum, tanaman tahan kering','Sorghum, drought-tolerant crops']], related:['so-07','so-09','so-12']
  },
  {
    id:'so-09', code:'SO-09', image:'assets/images/dust-memory.jpg', title:{id:'Debu Kering',en:'Dust Memory'}, scientific:'Dry loam · depleted surface', feelsShort:{id:'Berbubuk · Lepas · Pucat · Ringan',en:'Powdery · Loose · Pale · Light'}, usual:{id:'Jalur kering, lahan terbuka, tanah pascapanen',en:'Dry paths, exposed fields, post-harvest ground'}, crops:{id:'Millet, sorgum, legum, tanaman penutup',en:'Millet, sorghum, legumes, cover crops'}, quote:{id:'Debu menyimpan jejak tanah yang kehilangan kelembapan. Ia mudah terangkat oleh angin dan langkah.',en:'Dust holds the trace of soil that has lost moisture. It lifts easily with wind and footsteps.'}, voiceName:{id:'Catatan Debu Kering',en:'Dust Memory Note'}, duration:'01:06', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Debu kering menggambarkan permukaan tanah yang ringan, lepas, dan pucat. Ia dapat menandai tanah yang terbuka terlalu lama, kurang terlindungi, atau kehilangan bahan organik di permukaan.',en:'Dust memory describes a light, loose, pale soil surface. It can indicate ground left exposed too long, insufficient cover, or loss of surface organic matter.'}, feels:[['Tekstur','Texture','Halus, bubuk, mudah beterbangan','Fine, powdery, easily airborne'],['Berat','Weight','Sangat ringan','Very light'],['Kelembapan','Moisture','Hampir tidak terasa lembap','Almost no moisture felt'],['Sentuhan','Touch','Meninggalkan serbuk di jari','Leaves powder on fingers']], classification:[['Jenis','Type','Dry loam / depleted surface','Dry loam / depleted surface'],['Struktur','Structure','Lepas, rapuh, tidak terikat','Loose, fragile, unbound'],['Risiko','Risk','Erosi angin dan kehilangan lapisan atas','Wind erosion and topsoil loss'],['Catatan','Note','Membutuhkan penutup tanah atau bahan organik','Needs cover crops or organic matter']], source:[['Kategori','Category','Kualitas tanah terbuka-kering','Open-dry soil quality'],['Konteks','Context','Jalur kering, lahan pascapanen, tanah kosong','Dry paths, post-harvest fields, bare ground'],['Metode baca','Reading method','Debu, warna, ringan, bekas jari','Dust, colour, lightness, finger traces'],['Tanaman','Crops','Legum, tanaman penutup, sorgum','Legumes, cover crops, sorghum']], related:['so-08','so-10','so-11']
  },
  {
    id:'so-10', code:'SO-10', image:'assets/images/fine-grain.jpg', title:{id:'Butiran Halus',en:'Fine Grain'}, scientific:'Sandy · quartz-rich', feelsShort:{id:'Lepas · Granular · Ringan',en:'Loose · Granular · Light'}, usual:{id:'Tepi sungai, dataran pesisir, terasering dataran tinggi',en:'Riverbanks, coastal plains, terraced uplands'}, crops:{id:'Bawang merah, singkong, umbi, kacang tanah',en:'Shallots, cassava, root crops, peanuts'}, quote:{id:'Butiran halus mudah lepas dari genggaman. Ia tidak menahan bentuk lama, tetapi memberi ruang bagi akar bergerak.',en:'Fine grains slip easily from the hand. They do not hold shape for long, but give roots room to move.'}, voiceName:{id:'Catatan Butiran Halus',en:'Fine Grain Note'}, duration:'01:11', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Butiran halus menekankan rasa granular dan ringan. Kualitas ini membantu pengguna membedakan tanah yang lebih lepas dari tanah liat atau tanah yang terlalu padat.',en:'Fine grain emphasises a granular and light feeling. This quality helps users distinguish looser soil from clayey or compacted ground.'}, feels:[['Tekstur','Texture','Granular, berpasir, mudah lepas','Granular, sandy, easily loose'],['Berat','Weight','Ringan','Light'],['Kelembapan','Moisture','Cepat kering','Dries quickly'],['Sentuhan','Touch','Mengalir di antara jari','Flows between fingers']], classification:[['Jenis','Type','Sandy / quartz-rich soil','Sandy / quartz-rich soil'],['Struktur','Structure','Partikel kasar sampai sedang','Coarse to medium particles'],['Drainase','Drainage','Cepat','Fast'],['Risiko','Risk','Nutrisi dan air mudah hilang','Nutrients and water leach easily']], source:[['Kategori','Category','Kualitas granular-lepas','Loose granular quality'],['Konteks','Context','Tepi sungai, pesisir, upland tertentu','Riverbanks, coastal plains, some uplands'],['Metode baca','Reading method','Rubbing, aliran butir, berat','Rubbing, grain flow, weight'],['Tanaman','Crops','Umbi, kacang tanah, singkong','Root crops, peanuts, cassava']], related:['so-09','so-06','so-04']
  },
  {
    id:'so-11', code:'SO-11', image:'assets/images/hardened-ground.jpg', title:{id:'Tanah Mengeras',en:'Hardened Ground'}, scientific:'Laterite · iron-rich · compacted', feelsShort:{id:'Padat · Kering · Lithic · Resisten',en:'Solid · Dry · Lithic · Resistant'}, usual:{id:'Lereng terbuka, tanah gundul, lahan terdegradasi',en:'Exposed slopes, deforested ground'}, crops:{id:'Tanaman penutup restorasi, singkong, legum kuat',en:'Restoration cover crops, cassava, hardy legumes'}, quote:{id:'Tanah keras bukan hanya tekstur. Ia adalah tanda beban, waktu, air yang hilang, dan kerja yang bertambah.',en:'Hardened ground is not only a texture. It is a sign of pressure, time, lost water, and added labour.'}, voiceName:{id:'Catatan Tanah Mengeras',en:'Hardened Ground Note'}, duration:'01:17', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Tanah mengeras dibaca melalui resistensi. Ketika alat sulit masuk, tanah sedang memberi peringatan tentang pemadatan, kekeringan, atau kerusakan struktur.',en:'Hardened ground is read through resistance. When tools struggle to enter, the soil warns of compaction, dryness, or damaged structure.'}, feels:[['Tekstur','Texture','Keras, padat, kasar','Hard, compact, rough'],['Resistensi','Resistance','Sulit ditembus','Difficult to penetrate'],['Kelembapan','Moisture','Kering di permukaan','Dry at the surface'],['Warna','Colour','Merah, coklat besi, kusam','Red, iron-brown, dull']], classification:[['Jenis','Type','Laterite / compacted iron-rich soil','Laterite / compacted iron-rich soil'],['Struktur','Structure','Padat, berkerak, resisten','Dense, crusted, resistant'],['Drainase','Drainage','Permukaan dapat menolak air','Surface may repel water'],['Risiko','Risk','Akar sulit masuk, erosi meningkat','Root penetration is difficult, erosion increases']], source:[['Kategori','Category','Kualitas pemadatan dan degradasi','Compaction and degradation quality'],['Konteks','Context','Lereng terbuka, lahan gundul, tanah terlalu sering dilalui','Open slopes, bare ground, frequently trafficked soil'],['Metode baca','Reading method','Tekanan, alat, suara, warna besi','Pressure, tools, sound, iron colour'],['Tanaman','Crops','Tanaman penutup, singkong, legum kuat','Cover crops, cassava, hardy legumes']], related:['so-08','so-09','so-12']
  },
  {
    id:'so-12', code:'SO-12', image:'assets/images/salt-edge.jpg', title:{id:'Tepi Garam',en:'Salt Edge'}, scientific:'Saline · mineral-stressed', feelsShort:{id:'Berkerak · Pucat · Tajam · Kering',en:'Crusty · Pale · Sharp · Dry'}, usual:{id:'Lahan pesisir, tepi air payau, dataran pasang surut',en:'Coastal farms, brackish edges, tidal lowlands'}, crops:{id:'Kelapa, barley, rumput toleran garam',en:'Coconut, barley, salt-tolerant grasses'}, quote:{id:'Tepi garam terlihat seperti tanah yang memutih. Ia memberi tanda bahwa air, mineral, dan tekanan lingkungan bertemu di permukaan.',en:'Salt edge looks like soil turning pale. It signals where water, minerals, and environmental stress meet at the surface.'}, voiceName:{id:'Catatan Tepi Garam',en:'Salt Edge Note'}, duration:'01:14', language:{id:'Indonesia / Inggris',en:'Indonesian / English'}, note:{id:'Tepi garam adalah kualitas visual dan taktil yang diasosiasikan dengan kerak mineral atau tanah terdampak salinitas. Dalam arsip ini, ia dibaca secara hati-hati sebagai tanda tekanan mineral, bukan sebagai diagnosis tanah tanpa pengujian.',en:'Salt edge is a visual and tactile quality associated with mineral crust or salt-affected soil. In this archive, it is carefully read as a sign of mineral stress, not as a diagnosis without testing.'}, feels:[['Tekstur','Texture','Berkerak, kering, rapuh','Crusty, dry, brittle'],['Warna','Colour','Pucat, putih, beige','Pale, white, beige'],['Sentuhan','Touch','Tajam, kasar, mineral','Sharp, rough, mineral'],['Kelembapan','Moisture','Kering di permukaan, bisa lembap di bawah','Dry on surface, may be moist below']], classification:[['Jenis','Type','Saline-like / salt-affected surface','Saline-like / salt-affected surface'],['Kondisi','Condition','Mineral crust / coastal stress','Mineral crust / coastal stress'],['Drainase','Drainage','Bervariasi, sering terkait air payau','Varies, often linked to brackish water'],['Catatan','Note','Perlu uji salinitas untuk konfirmasi','Salinity test needed for confirmation']], source:[['Kategori','Category','Kualitas mineral-pesisir','Coastal-mineral quality'],['Konteks','Context','Pesisir, tepi air payau, dataran pasang surut','Coastal farms, brackish edges, tidal lowlands'],['Metode baca','Reading method','Kerak, warna pucat, rasa kering, tekstur mineral','Crust, pale colour, dryness, mineral texture'],['Tanaman','Crops','Kelapa, tanaman toleran garam','Coconut, salt-tolerant plants']], related:['so-08','so-11','so-09']
  }
];

function entryById(id){ return entries.find(e=>e.id===id) || entries[0]; }
function formatTitle(entry){ return L(entry.title); }
function splitTitle(entry){ return L(entry.title).replace(' ', '<br>'); }

function render(){
  document.documentElement.lang = LANG;
  const route = location.hash.replace(/^#\/?/, '');
  const app = document.getElementById('app');
  app.innerHTML = route && entryById(route)?.id === route ? renderEntry(entryById(route)) : renderIndex();
  bindLang();
  window.scrollTo(0,0);
}

function renderTop(currentCode=''){
  return `<div class="wrap"><nav class="topline"><a href="#/">← ${t('index')}</a><span>${currentCode}</span></nav></div>`;
}
function renderLang(){ return `<div class="lang"><button class="${LANG==='id'?'active':''}" data-lang="id">ID</button><button class="${LANG==='en'?'active':''}" data-lang="en">EN</button></div>`; }
function footer(){ return `<div class="wrap"><footer class="footer"><span>${t('version')}</span><p>${t('contribute')}</p>${renderLang()}</footer></div>`; }
function renderIndex(){
  const cards = entries.map(e=>`<a class="card" href="#/${e.id}"><span class="card-img" style="background-image:url('${e.image}')"></span><span class="card-info"><span class="code">${e.code}</span><h2>${splitTitle(e)}</h2><p class="sci">${e.scientific}</p><p class="feels">${L(e.feelsShort)}</p></span></a>`).join('');
  return `<section class="wrap"><div class="hero-index"><p class="mini">${t('soilArchive')}</p><h1>THE<br>SOIL<br>ARCHIVE</h1><p class="cover-note">${t('subtitle')}</p><p class="logic">${t('logic')}</p></div><div class="archive-intro"><span class="label">VOL. 01</span><p>${t('intro')}</p></div><div class="grid">${cards}</div></section>${footer()}`;
}
function rows(data){ return data.map(r=>`<dt>${LANG==='id'?r[0]:r[1]}</dt><dd>${LANG==='id'?r[2]:r[3]}</dd>`).join(''); }
function section(title, data){ return `<section class="section"><h3 class="section-title">${title}</h3><dl class="meta-list">${rows(data)}</dl></section>`; }
function renderEntry(e){
  const related = e.related.map(id=>{ const r=entryById(id); return `<a class="related-card" href="#/${r.id}"><span class="thumb" style="background-image:url('${r.image}')"></span><span class="r-code">${r.code}</span><p class="r-title">${formatTitle(r)}</p></a>`; }).join('');
  return `${renderTop(e.code)}<section class="wrap entry"><div class="entry-grid"><aside class="media"><div class="soil-photo" style="background-image:url('${e.image}')"><span class="caption">${e.scientific}</span></div></aside><article class="entry-body"><header class="entry-head"><p class="code">${e.code}</p><h1>${formatTitle(e)}</h1><p class="sci">${e.scientific}</p></header><button class="voice" onclick="playVoice('${e.id}', this)"><span class="play"><svg viewBox="0 0 16 16" fill="currentColor"><path d="M4 2.5v11l9-5.5z"/></svg></span><span><span class="voice-title">${L(e.voiceName)}</span><p class="voice-meta">${e.duration} · ${L(e.language)}</p></span></button><blockquote class="quote"><p class="main">“${L(e.quote)}”</p>${LANG==='id'?`<span class="translation">“${e.quote.en}”</span>`:''}</blockquote><section class="section"><h3 class="section-title">${t('note')}</h3><p class="archive-note">${L(e.note)}</p></section>${section(t('feels'), e.feels)}${section(t('classification'), e.classification)}${section(t('source'), e.source)}<section class="section"><h3 class="section-title">${t('usually')}</h3><dl class="meta-list"><dt>${LANG==='id'?'Lokasi':'Location'}</dt><dd>${L(e.usual)}</dd><dt>${t('crops')}</dt><dd>${L(e.crops)}</dd></dl></section><section class="section"><h3 class="section-title">${t('related')}</h3><div class="related-grid">${related}</div></section></article></div></section>${footer()}`;
}
function voiceText(e){
  if(LANG==='id') return `${e.code}. ${e.title.id}. ${e.note.id}. Rasanya: ${e.feelsShort.id}. Biasanya ditemukan di ${e.usual.id}. Tanaman yang mendukung: ${e.crops.id}.`;
  return `${e.code}. ${e.title.en}. ${e.note.en}. It feels: ${e.feelsShort.en}. Usually found in ${e.usual.en}. Often supports: ${e.crops.en}.`;
}
function playVoice(id, btn){
  const e = entryById(id);
  if(!('speechSynthesis' in window)) return alert('Speech synthesis is not supported in this browser.');
  window.speechSynthesis.cancel();
  const u = new SpeechSynthesisUtterance(voiceText(e));
  u.lang = LANG==='id' ? 'id-ID' : 'en-US';
  u.rate = LANG==='id' ? .88 : .9;
  currentUtterance = u;
  window.speechSynthesis.speak(u);
}
function bindLang(){ document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{ LANG=b.dataset.lang; window.speechSynthesis?.cancel(); render(); }); }
window.addEventListener('hashchange', render);
render();
